### ISSUE TITLE
Bug: `phone` field does not account for numbers starting with 0

### ISSUE THREAD

**Issue by weiliann** [AY2425S1-CS2103T-F11-2/tp#112]
Issue:
Numbers starting with 0s are accepted which might not be intended

Reproduce:
`add n/John Doe p/00000000 e/johnd@example.com t/johnDoe12 r/Exco Member f/`

**Comment by shizy** [comment]
<img width="735" alt="Screenshot 2024-10-29 at 14 01 09" src="https://github.com/user-attachments/assets/cfe6dcd6-8846-4864-b77a-76ae1116f002">
If we want to purely restrict numbers to valid singapore numbers, we could restrict it to start with 3, 6, 8 or 9

One possible issue is that this can be considered a feature flaw also, if they think we are being too overzealous with input validation
