### ISSUE TITLE
potential bug: `email` field may reject a valid email address

### ISSUE THREAD

**Issue by weiliann** [AY2425S1-CS2103T-F11-2/tp#114]
Currently only these special characters (+_.-) are allowed for the {local-part} but a technically valid local-part also accepts these special printable characters ```!#$%&'*+-/=?^_`{|}~``` [full doc for valid address](https://en.wikipedia.org/wiki/Email_address#Sub-addressing:~:text=Force%20(IETF).-,Local%2Dpart,-%5Bedit%5D)

while technically valid, many applications out there don't account for these special characters. Particularly, this is the regex that the Singapore government uses for their application. [src](https://www.designsystem.tech.gov.sg/patterns/email-address#:~:text=Email%20Address-,Email%20Address,-Use%20this%20pattern)
`pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$"`

Also this leads to a rabbit hold of valid email addresses because there is unquoted and quoted address. Quoted address become much more complex to validate, although there is an article showing a solution [here](https://www.prosiglieres.com/posts/rfc-compliant-email-address-validation/).

I'm not sure if it is worth to support all these 'valid' email address but I thought it is worth to highlight them.

**Comment by shizy** [comment]
Don't think its in our best interests to support this email spec, since this will just compound our test cases + muddy the valid explanation
I think the current implementation is quite similar to the sg gov implementation, with the exception of currently not allowing the % char
I could add that in
