### ISSUE TITLE
Bug: Message change when type only `sw` or `switch`

### ISSUE THREAD

**Issue by Rachelcoll** [AY2425S1-CS2103T-F11-2/tp#116]
Expected behavior of switch should be `switch {profile-name}`, currently typing single `switch` or `sw` will simply list all the current addressbook, which is a bit confusing and user may not understand how to use this command. Maybe it would be better if the app can throw a parser exception to require user to input new addressbook name and give the addressbook list in current message for the user to choose if they only type in `switch` or `sw`
![image](https://github.com/user-attachments/assets/ca965e99-073d-4a2a-9aa0-b117d14d480f)

**Comment by weiliann** [comment]
ok i will change it. thanks for the feedback
