### ISSUE TITLE
Ui Bug: Different Roles are listed without space in list view

### ISSUE THREAD

**Issue by Rachelcoll** [AY2425S1-CS2103T-F11-2/tp#117]
When creating a member with multiple roles (eg. `a n/test2 t/... e/.. p/... r/Exco r/Member`, all the listed contact's roles are concatenated together, which can't distinguish from contact with role like `a n/test1 t/... e/.. p/... r/ExcoMember`.

![image](https://github.com/user-attachments/assets/c81d9318-0988-418d-9f61-16d46dc7a241)

**Comment by superb-sushi** [comment]
Issue raised in #106
