### ISSUE TITLE
bug: `mark` command contains grammatical error

### ISSUE THREAD

**Issue by weiliann** [AY2425S1-CS2103T-F11-2/tp#123]
![image](https://github.com/user-attachments/assets/7beeffe5-7ed7-47e5-8d72-24918bd111e9)

-should be 'marked' 

-when a single person is marked it feels abit off to also display `'these people: [alex yeoh]'`. maybe can show `'this person: [alex yeoh]'` ? idk up to your discretion.

**Comment by Rachelcoll** [comment]
That's because you can mark multiple people once, so they will all be listed here. But I can change to format like people(person). Thanks for the reveiw.
