### ISSUE TITLE
Bug: `delete` command specifies wrong error message when an integer > INT_MAX is specified as index

### ISSUE THREAD

**Issue by shizy** [AY2425S1-CS2103T-F11-2/tp#130]
Steps to reproduce:
1. Enter `delete 2147483648` as a command
<img width="743" alt="Screenshot 2024-10-30 at 23 01 41" src="https://github.com/user-attachments/assets/484488f7-c7db-49ba-a600-090a833cf57a">

Currently, if the user enters `delete 2147483647` as a command, the invalid index error is displayed (this is expected behaviour)
<img width="744" alt="Screenshot 2024-10-30 at 23 03 55" src="https://github.com/user-attachments/assets/c79799c2-f950-4f48-9f84-3d4078d5bcc2">

However, on entering `delete 2147483648`, the invalid command format error is displayed. This should not be the case

**Comment by weiliann** [comment]
I think it is safe to ignore this 'bug' based on previous years pe. a group attempted to report this as a bug but got rejected. [src](https://github.com/nus-cs2103-AY2021S2/pe-dev-response/issues/3128)

![image](https://github.com/user-attachments/assets/6f037beb-f5ca-4a08-8fc8-106a99766931)
