### ISSUE TITLE
Bug/Potential Spec Issue: `list` allows for users to input parameters

### ISSUE THREAD

**Issue by shizy** [AY2425S1-CS2103T-F11-2/tp#135]
Steps to reproduce:
1. Enter `list xyz`
<img width="654" alt="Screenshot 2024-10-30 at 23 47 23" src="https://github.com/user-attachments/assets/10a3d660-0e71-4cda-97e1-7ee0bdac888f">

Currently, it is specified that `list` takes in no parameters, as per the `help` command. However, the `list` command currently does not check for parameters, meaning users can input anything they want after and have it be valid

Functionally, writing additional parameters does not do anything, but it might be clearer to mark such instances as erroneous (with an error message like "list does not take in additional parameters"), just in case the user might be confused as to what the `list` command actually does 
E.g. users input `list r/test` mistakenly trying to get the functionality of `view r/test`

**Comment by weiliann** [comment]
should we just update the ug instead?
