### ISSUE TITLE
Bug/Potential Spec Issue: `help` allows for users to input parameters

### ISSUE THREAD

**Issue by shizy** [AY2425S1-CS2103T-F11-2/tp#136]
Similar to Issue #135 

Steps to reproduce:
1. Enter `help x`

On entering `help` with parameters, the help window appears as per usual. In the specs, it is stated that `help` takes in no parameters

If we want to restrict `help` to have no parameters, it might be good to display an error message like "help takes in no additional parameters", to make it clear to the user that adding additional parameters should not happen

**Comment by weiliann** [comment]
i plan to mention in the user guide that extraneous arguments will be ignored for. this should give some flexibility for the users
