### ISSUE TITLE
Bug: `edit` command specifies wrong error message when an integer > INT_MAX is specified as index

### ISSUE THREAD

**Issue by shizy** [AY2425S1-CS2103T-F11-2/tp#146]
Related to issue #130 

Steps to reproduce:

1. Enter `edit 2147483648 n/test` as a command
<img width="741" alt="Screenshot 2024-10-31 at 01 42 27" src="https://github.com/user-attachments/assets/6586760e-953e-49b0-8889-52f1d81fba7e">

Currently, if the user enters `edit 2147483647 n/test` as a command, the invalid index error is displayed (this is expected behaviour)
<img width="740" alt="Screenshot 2024-10-31 at 01 42 52" src="https://github.com/user-attachments/assets/ccb93a13-8a63-434d-bfc6-4809ef0c164c">

However, on using the index 2147483648 (which is > INT_MAX), the invalid command format error is displayed. This should not be the case

**Comment by weiliann** [comment]
should not be a bug [src](https://github.com/nus-cs2103-AY2021S2/pe-dev-response/issues/3128)
