### ISSUE TITLE
Bug: "!!" is a valid name 

### ISSUE THREAD

**Issue by yyihaoc** [AY2425S1-CS2103T-F11-2/tp#174]

**Comment by shizy** [comment]
I feel that its really up to the user if they want to make the name `!!`. E.g. in your phone contact app, it also allows for you to put in names that don't really exist, but you would not consider that a bug.

I don't think in the PE, this will be considered a valid bug

If you really want we could specify that names must contain at least one alphabet, but then again `a!!` also would not be a proper name
