### ISSUE TITLE
`find` by telegram handle causes the app to break if invalid telegram handle is used

### ISSUE THREAD

**Issue by shizy** [AY2425S1-CS2103T-F11-2/tp#175]
Steps to reproduce:
Before:
<img width="512" alt="Screenshot 2024-11-06 at 19 22 47" src="https://github.com/user-attachments/assets/050645ac-7602-4e9f-92ea-2bb3d6aa96b9">
1. Enter `find` with an invalid telegram handle (<5 characters or >32 characters)
`find abcd`
System throws unhandled `InvocationTargetException`
<img width="1323" alt="Screenshot 2024-11-06 at 19 25 09" src="https://github.com/user-attachments/assets/e1024ed7-ab09-47cb-a50a-d46110218b30">

2. Enter `list`
Contact list view is now broken
<img width="512" alt="Screenshot 2024-11-06 at 19 25 44" src="https://github.com/user-attachments/assets/7ffa8519-6ff8-4a11-b60f-77f5dacaea43">
Notice that the list is now repeating twice (previously there were only 4 contacts)

**Comment by yyihaoc** [comment]
I think it should be fixed in the pr #158
