### ISSUE TITLE
[PE-D][Tester B] Class diagram notation

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F11-2/tp#244]
![image.png](https://raw.githubusercontent.com/DiegoTheExplorar/ped/main/files/da4f5c8a-05e3-4955-aeb3-8f76e5542f54.png)

the access modifier notation used is not what is taught in this module

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: DiegoTheExplorar/ped#13

**Comment by weiliann** [comment]
duplicate of #265
